services:
  db:
    #    platform: linux/x86_64
    image: postgres:17.4-alpine
    container_name: postgres_17
    restart: always
    environment:
      - POSTGRES_DB=colvir
      - POSTGRES_USER=colvir
      - POSTGRES_PASSWORD=colvir
    ports:
      - '5432:5432'
    volumes:
      - ./db/spareparts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/spareparts/postgres-volume:/var/lib/postgresql/data