spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/colvir
    username: colvir
    password: colvir
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate.format_sql: true